Repository osamhack2020/APP_KookMoBanUser_PonJohmNaimann, pull requests merged in 2020-10, with the labels that each got.

#12 ENH : 병사 등록시 나오는 Toast 메시지에서 이름의 값이 잘못들어가 있는 오류 수정
  app/src/main/java/com/ponjohmnaimann/kookmobanuser/SharedPreferenceData.kt
Labels: android, bug

#17 [CLN] 토스트 제거
  .idea/terminal.xml
  app/src/main/java/com/ponjohmnaimann/kookmobanuser/LoggedInMainActivity.kt
  app/src/main/java/com/ponjohmnaimann/kookmobanuser/MainActivity.kt
  app/src/main/java/com/ponjohmnaimann/kookmobanuser/QRcodeActivity.kt
Labels: android, cleanup

#27 [ENH] TOTP값 표시 토스트 메시지 추가
  app/src/main/java/com/ponjohmnaimann/kookmobanuser/QRcodeActivity.kt
Labels: android, enhancement

#21 [ENH] Time-based OTP값이 변할때마다 QRCode를 새로고침
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ponjohmnaimann/kookmobanuser/MainActivity.kt
  app/src/main/java/com/ponjohmnaimann/kookmobanuser/QRCodeGenerator.kt
  app/src/main/java/com/ponjohmnaimann/kookmobanuser/QRcodeActivity.kt
  app/src/main/java/com/ponjohmnaimann/kookmobanuser/ReturnSuccessCheck.kt
  app/src/main/java/com/ponjohmnaimann/kookmobanuser/SharedPreferenceData.kt
  app/src/main/res/layout/activity_q_rcode.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: android, enhancement

#41 Create build.yml
  .github/workflows/build.yml
  readme.md
Labels: android, enhancement

#42 Update readme.md
  readme.md
Labels: bug

#43 Update README.md
  README.md
Labels: cleanup

#44 Update README.md
  README.md
Labels: cleanup
